{% set name = "sqlparse" %}
{% set version = "0.4.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d446183e84b8349fa3061f0fe7f06ca94ba65b426946ffebe6e3e8295332420c

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - sqlformat = sqlparse.__main__:main

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
  run:
    - python

test:
  imports:
    - sqlparse
  requires:
    - pip
  commands:
    - pip check
    - sqlformat --help

about:
  home: https://github.com/andialbrecht/sqlparse
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A non-validating SQL parser module for Python.
  description: |
    sqlparse is a non-validating SQL parser for Python. It provides support
    for parsing, splitting and formatting SQL statements.
  doc_url: https://sqlparse.readthedocs.io
  dev_url: https://github.com/andialbrecht/sqlparse

extra:
  recipe-maintainers:
    - ocefpaf
