{% set name = "sqlparse" %}
{% set version = "0.5.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 09f67787f56a0b16ecdbde1bfc7f5d9c3371ca683cfeaa8e6ff60b4807ec9272

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - sqlformat = sqlparse.__main__:main

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python

test:
  imports:
    - sqlparse
  requires:
    - pip
  commands:
    - pip check
    - sqlformat --help

about:
  home: https://github.com/andialbrecht/sqlparse
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A non-validating SQL parser module for Python.
  description: |
    sqlparse is a non-validating SQL parser for Python. It provides support
    for parsing, splitting and formatting SQL statements.
  doc_url: https://sqlparse.readthedocs.io
  dev_url: https://github.com/andialbrecht/sqlparse

extra:
  recipe-maintainers:
    - ocefpaf
