{% set name = "sqlparse" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 113c35c75365ab9cc9c7231d68c6428fb11c085fc8e9eb1ad659b7ddbf6cd2b9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - sqlformat = sqlparse.__main__:main
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - sqlparse
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - sqlformat --help
    - pytest -v tests

about:
  home: https://github.com/andialbrecht/sqlparse
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A non-validating SQL parser module for Python.
  description: |
    sqlparse is a non-validating SQL parser for Python. It provides support
    for parsing, splitting and formatting SQL statements.
  doc_url: https://sqlparse.readthedocs.io
  dev_url: https://github.com/andialbrecht/sqlparse

extra:
  recipe-maintainers:
    - ocefpaf
