# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GA89ctAGMYLDQ7/rSqJUexhTKNmq5/0+50dG3mIGG7VIqoSOHCsBfErhrBRrrEC7u4zO349FQmIrbB28UWY/mxFRSYHHBtW+DGYB7YvAQ6HkqWCpc3+AojgfkscsFokBYpkNYw4wnA26ucfKez0VJyJ9Jlwmd/sErBQtIjFb3y/GiU3TOlUiJFRmAIvrcxg+oplRF9pdbnok2COMXRPdhqx0ipZYmkEMxt4eQnvcI4OKWEiknUVIKs+Hhp1k56vrramwJoEb4+Cf3fLBQ17WOiZl3hQI8aKqsMNsFvj/jLw+dci9ocNCqiBE3uR6cbl/8uQVgIBdPbarliBj/2AjIoGhuEjy60QzfBFOdphQlV9gCoCUO1rzRIEBnbzldcHZIWQn/QnBA8OpbWia1K54b7w8J0S+jQtAbwxsYtw4Y8jja5mmK8atw3aBfqrs7dBPW81ooE8x8n8ZN8d3E30eKFd4nUqymuvZc2U3je+3Q52ThuqrnZ/kaSWlhZyFphlqXuvCwj/4Hg6h/RfCjJoVMyxSNXHX6qpRvPsgE/K3RNLk93PVHvCGPrRi3chI5Q7Fpc6iuuBMSmPr9R5pRR+58PPhP9i6HJr1hm76koeYsAuS471c9brBpv1n0f/AfzJA9pFr9lpFJD3Lfb5RpJ6QbEl7yMJwBOl2pa+ZPaLCPDc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
