travis:
  secure:
    BINSTAR_TOKEN: hc8yCCUUm4YnzGHr+U9Uj47DzQwCem1F7Tm4lMAbAZ8KxAaYTZjHuJ27ZxixSe4fiVKQ1/IO6OOF+/JjTN/zM4xB9XSKl7P2CtJ6Q9kYjp1jD85bUVHo3LdUMp6A24/89SinLija2XX/gBe+La0LcJs1nRVrxRJf5A26nJIaffHf3lPQtG45jSKADsc6kiK1qrTS0OBbstCxutjhe7xkdgjG2+GjbywdNxPpKDoCuUVwgIM9Y/USqrhQXVClgTO2D1NID7BD5Odl5DKGZX4c1CUvQIHzKj0BBEimI1YNbXum5Rlaktbf7ahQDP4USFUaL24hm4+htBD4uMowvidS2K217PAZrt1IEmz6kZfiFbicffJ/rPzK5gCzNtHGtW/sDwkaIQsfEkUh4uWqIz9Ycms7uP7qRX2FZUtM6GmdSUUFCnfPsj749KOKU52N9vSQ47rI4Dcy2Br4ibdWcv71d8qciSVsz+aGvT0bB6wWLrvq+WFwo3T7nVRV3Fr4Ey9i2ap13BH5/qZdR3FFSQrlb18Uy0f+dYcqSJpEkSfTewXtLffDxnhHRbOdjB70QPwt2bvyVdsCi0Tu+R95nGD1h+GNE12LKCc75+xjC5gQg4h1IpAdd9vm6labso8WHzJqJZuFt5i9uCAYAB2etiXiUepKgIk8KvjpdowToLKK1gA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
