travis:
  secure:
    BINSTAR_TOKEN: GA89ctAGMYLDQ7/rSqJUexhTKNmq5/0+50dG3mIGG7VIqoSOHCsBfErhrBRrrEC7u4zO349FQmIrbB28UWY/mxFRSYHHBtW+DGYB7YvAQ6HkqWCpc3+AojgfkscsFokBYpkNYw4wnA26ucfKez0VJyJ9Jlwmd/sErBQtIjFb3y/GiU3TOlUiJFRmAIvrcxg+oplRF9pdbnok2COMXRPdhqx0ipZYmkEMxt4eQnvcI4OKWEiknUVIKs+Hhp1k56vrramwJoEb4+Cf3fLBQ17WOiZl3hQI8aKqsMNsFvj/jLw+dci9ocNCqiBE3uR6cbl/8uQVgIBdPbarliBj/2AjIoGhuEjy60QzfBFOdphQlV9gCoCUO1rzRIEBnbzldcHZIWQn/QnBA8OpbWia1K54b7w8J0S+jQtAbwxsYtw4Y8jja5mmK8atw3aBfqrs7dBPW81ooE8x8n8ZN8d3E30eKFd4nUqymuvZc2U3je+3Q52ThuqrnZ/kaSWlhZyFphlqXuvCwj/4Hg6h/RfCjJoVMyxSNXHX6qpRvPsgE/K3RNLk93PVHvCGPrRi3chI5Q7Fpc6iuuBMSmPr9R5pRR+58PPhP9i6HJr1hm76koeYsAuS471c9brBpv1n0f/AfzJA9pFr9lpFJD3Lfb5RpJ6QbEl7yMJwBOl2pa+ZPaLCPDc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
